# Generated by Django 3.0.2 on 2020-01-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Aadhar_Number',
            field=models.CharField(default=1234, max_length=12),
            preserve_default=False,
        ),
    ]
