# Generated by Django 2.2.4 on 2020-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0002_people_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='people',
            name='EmailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
