# Generated by Django 2.2.4 on 2020-01-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0005_auto_20200104_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='Latitude',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='Longitude',
            field=models.FloatField(default=2.1),
            preserve_default=False,
        ),
    ]
