# Generated by Django 2.2.4 on 2020-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0006_auto_20200108_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='City',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Latitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='people',
            name='Longitude',
            field=models.FloatField(default=-1),
        ),
    ]
