# Generated by Django 2.2.4 on 2020-01-08 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0007_auto_20200108_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='LocationDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
