# Generated by Django 2.2.4 on 2020-01-08 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0009_auto_20200108_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='LocationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 5, 7, 36, 480880, tzinfo=utc)),
        ),
    ]
