# Generated by Django 2.2.4 on 2020-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0010_auto_20200108_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='LocationDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
