# Generated by Django 2.2.4 on 2020-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0011_auto_20200109_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='RecoveryMail',
            field=models.EmailField(default='recovery@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='RecoveryNumber',
            field=models.CharField(default='11111', max_length=13),
            preserve_default=False,
        ),
    ]
