# Generated by Django 2.2.4 on 2020-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0012_auto_20200109_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Age',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
