# Generated by Django 2.2.4 on 2020-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0013_people_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='RecoveryMail',
            field=models.EmailField(max_length=254),
        ),
    ]
