# Generated by Django 2.2.4 on 2020-01-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0014_auto_20200109_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='RecoveryMail',
        ),
    ]
