# Generated by Django 2.2.4 on 2020-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0015_remove_people_recoverymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='RecoveryMail',
            field=models.EmailField(default='recovery@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
