# Generated by Django 2.2.4 on 2020-01-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0016_people_recoverymail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(default=-1)),
                ('Longitude', models.FloatField(default=-1)),
                ('City', models.CharField(default='Unknown', max_length=50)),
                ('Added_at', models.DateTimeField(auto_now_add=True)),
                ('Action_taken', models.BooleanField(default=False)),
                ('Action_taken_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
