# Generated by Django 2.2.4 on 2020-01-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0023_auto_20200118_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio',
        ),
        migrations.AddField(
            model_name='audio',
            name='aud',
            field=models.FileField(default='defalut', upload_to='sih/audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personinneed',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
